export enum NFL_PLAY {
    TOUCHDOWN = "TOUCHDOWN",
    FIELD_GOAL_GOOD = "FIELD_GOAL_GOOD",
    FIELD_GOAL_MISSED = "FIELD_GOAL_MISSED",
    EXTRA_POINT_GOOD = "EXTRA_POINT_GOOD",
    EXTRA_POINT_MISSED = "EXTRA_POINT_MISSED",
    SAFETY = "SAFETY",

}